# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=release
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),release)
  GMad_config = release
endif

PROJECTS := GMad

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

GMad:
ifneq (,$(GMad_config))
	@echo "==== Building GMad ($(GMad_config)) ===="
	@${MAKE} --no-print-directory -C . -f GMad.make config=$(GMad_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f GMad.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   GMad"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"